provider:
  name: openfaas
functions:
  mptosvg:
    image: ghcr.io/pandora-mccme/latex-fn:main
    fprocess: "mptosvg"
    environment:
      content_type: "application/octet-stream"
      exec_timeout: 3m
      read_timeout: 3m
      write_timeout: 3m
    labels:
      com.openfaas.ui.ext: "svg"
    limits:
      memory: 128Mi
      cpu: 1000m
    requests:
      memory: 20Mi
      requests: 100m
  latextopdf:
    image: ghcr.io/pandora-mccme/latex-fn:main
    fprocess: "latextopdf"
    environment:
      content_type: "application/octet-stream"
      exec_timeout: 3m
      read_timeout: 3m
      write_timeout: 3m
    labels:
      com.openfaas.ui.ext: "pdf"
    limits:
      memory: 128Mi
      cpu: 1000m
    requests:
      memory: 20Mi
      requests: 100m
  ziplatextopdf:
    image: ghcr.io/pandora-mccme/latex-fn:main
    fprocess: "ziplatextopdf"
    environment:
      content_type: "application/octet-stream"
      exec_timeout: 3m
      read_timeout: 3m
      write_timeout: 3m
    labels:
      com.openfaas.ui.ext: "pdf"
    limits:
      memory: 128Mi
      cpu: 1000m
    requests:
      memory: 20Mi
      requests: 100m
